### ISSUE TITLE
how to add another mikrotik device

### ISSUE THREAD

**Issue by helospro** [IgorKha/Grafana-Mikrotik#22]
Hello, i want to add another mikrotik device.

what should i do ?

thanks

![Screenshot from 2022-09-14 11-55-10](https://user-images.githubusercontent.com/100141161/190062886-acbef5a6-500d-4508-af9d-e414d5d92c7f.png)

**Comment by yyovkov** [comment]
If the IP addresses are suitable for you, you can use such kind of block in your `prometheus.yaml`, when using `snmp_exporter`:

```
  - job_name: 'mikrotik'
    static_configs:
      - targets:
         - 1.2.3.4
         - 5.6.7.8
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
        ```
