### ISSUE TITLE
The instance field in the dashboard

### ISSUE THREAD

**Issue by alexanderek** [IgorKha/Grafana-Mikrotik#25]
Hi

How can the instance field (Grafana) see the System identity, or the hostname of the device instead of the IP address?

**Comment by IgorKha** [comment]
Hey! Try replacing the target's ip with its name, by which it is available on the network
[prometheus/prometheus.yml](https://github.com/IgorKha/Grafana-Mikrotik/blob/aa802b1c36cb167edc7592ffd5eabba7b61e8105/prometheus/prometheus.yml#L44)
### Example:
```yml
......
- job_name: Mikrotik
    static_configs:
      - targets:
        - myrouter.lan # <---- In this place
    metrics_path: /snmp
.....
```
