### ISSUE TITLE
Multiple equipment

### ISSUE THREAD

**Issue by borsoy** [IgorKha/Grafana-Mikrotik#27]
Hi! How i can use more than one mikrotik for monitoring?
I am added some hosts in config:
----------------------------------
```
- job_name: Mikrotik
    static_configs:
      - targets:
        - 172.16.1.254 # LER130
        - 172.16.6.254 # CHONA
        - 172.16.7.254 # SDM

   metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mk_snmp_exporter:9116
```
----------------------------------------------
but i didn't see it in dropbox of grafana

RouterOS version: 6.48.6
