### ISSUE TITLE
RouterSO v7 not showing System Info

### ISSUE THREAD

**Issue by rackifiaustin** [IgorKha/Grafana-Mikrotik#29]
Hello,

I have a CCR2216 and when I use your exporter, I do not see certain parts.

System is fully marked "No Data" except the Uptime

How can I fix this?

**Comment by jiimint** [comment]
Hi,
I have the same issue with RB4011 Ros7.7
"No Data" except Uptime.

**Comment by lwijnsma** [comment]
After some digging in the `snmp.yml` file. I edited the params section of the  Mikrotik scrape  job in the `prometheus.yml` file to look like this: 
```yaml
params:
  module:
    - if_mib
    - system
    - hrSystem
    - hrDevice
    - hrStorage
    - mikrotik
```
With these added modules the grafana dashboard starts to show more of the System stats.
